.DEFAULT_GOAL := help
.PHONY: help

VERSION=$(shell cat ./VERSION)

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

build: ## Build the application
	CGO_ENABLED=0 go build -ldflags="-X 'main.Version=${VERSION}'" -mod=mod -o server .

start: ## Run everything locally in Docker
	docker compose up --build

docker-tag: ## Builds a docker image and tags a release. It is then pushed up to Docker. GITHUB_TOKEN must be defined as an environment variable. make USERNAME="username" docker-tag
	@echo "Building ${VERSION}"
	echo $$GITHUB_TOKEN | docker login ghcr.io -u ${USERNAME} --password-stdin && docker buildx use mybuilder
	docker buildx build -f Dockerfile --platform linux/amd64,linux/arm64 --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t {{.DockerRegistryPath}}:${VERSION} --push .

